# Generated by Django 4.1.7 on 2023-03-29 11:34

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=portfolio.models.PathAndRename('/projects_images')),
        ),
    ]
