# Generated by Django 4.1.7 on 2023-07-01 21:48

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_logo_alter_project_picture_projectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_roles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=portfolio.models.PathAndRename('projects_logos/')),
        ),
    ]
